### PR TITLE
Update StaffChatCommand.java

### PR DESCRIPTION
**Pull request by MODKILLER1001**
change &f to &r may be helpful in future

### CODE REVIEW

**Comment by BennyDoesTheStuff** [comment]
This is literally, the stupidest pull request so far -_-

**Comment by dannygtech** [comment]
as far as I know &r = &f anyways, well that's how it is on Minehut plugins ):

**Comment by Draem** [comment]
&r is white, &f is white.

**Comment by RONTheCookie** [comment]
&r "resets" the color, &f is white.

**Comment by Draem** [comment]
Same difference. Resetting turns it to white. &f turns it to white.

**Comment by RONTheCookie** [comment]
I know, just wanted to point it out.

**Pull request closed without merging**
