### PR TITLE
nothing 2 see here

### PR DESCRIPTION
**Pull request by Bayside308**
good commit, must-have, wow

### CODE REVIEW

**Comment by Draem** [comment]
no <3

**Comment by Pixelific** [comment]
I don't know why draem closed this issue, clearly your contributed code is amazing for warvale, I especially like the "op dividedwefall" part, I don't even know what it means so that means it's quality code!

**Comment by Bayside308** [comment]
clearly u must place this draem guy with me

**Comment by Draem** [comment]
This pull request will be added if our third developer agrees. 

However, if he disagrees, this pull request will be terminated and you will be blacklisted from ever creating pull requests again.

**Thanks, 
Draem**

**Comment by Pixelific** [comment]
Request declined

**Comment by Draem** [comment]
Our fourth surprise developer ( @Pixelific ) has denied this pull request.

**Comment by Draem** [comment]
After reviewing this pull request, I've realized that it could be a good addition, but requires a bit more work before it will be added.

These fixes are as followed:
- Remove **"op DividedWeFall"**
- Add **"op Bayside308"**
- Create async system for giving players op.
- Add elaborate system for creating MySQL "Where" statements.
                _Think: Where#.var(String).equalTo(Object)_
- Allow rank system to change prefixes and suffixes without having a player to relog.

**Pull request closed without merging**
